spring.application.name=sistema-aluguel-api

spring.datasource.url=jdbc:mysql://localhost:3306/sistema_aluguel
spring.datasource.username=root
spring.datasource.password=nova_senha
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=3f8a9b2c1d7e6f4a5b8c3d2e1f9a7b6c5d4e3f2a1b8c7d6e5f4a3b2c1d9e8f7
jwt.expiration=86400000